
version: '2.1'
services:
  logstash-develop:
    build:
      args:
      - IMAGE_ARG_LOGSTASH_IMAGE_NAME=${IMAGE_ARG_LOGSTASH_IMAGE_NAME:-logstash}
      - IMAGE_ARG_LOGSTASH_IMAGE_VERSION=${IMAGE_ARG_LOGSTASH_IMAGE_VERSION:-5.6.10}
      context: .
      dockerfile: Dockerfile
    container_name: ${CONTAINER_HOST_NAME:-standalone.elk}-logstash
    environment:
    - INPUT_REDIS_HOST=${INPUT_REDIS_HOST:-standalone.elk}-logstash-redis
    - INPUT_REDIS_PORT=${INPUT_REDIS_PORT:-6379}
    - INPUT_JSON_TCP_PORT=${INPUT_JSON_TCP_PORT:-51401}
    - INPUT_LINE_TCP_PORT=${INPUT_LINE_TCP_PORT:-51402}
    - OUTPUT_ELASTICSEARCH_HOSTS=${OUTPUT_ELASTICSEARCH_HOSTS:-standalone.elk-elasticsearch:9200}
    hostname: ${CONTAINER_HOST_NAME:-standalone.elk}-logstash
    image: cirepo/logstash:${IMAGE_TAG:-5.6.10} #6.2.3
    #image: docker.elastic.co/logstash/${IMAGE_ARG_LOGSTASH_IMAGE_NAME:-logstash}:${IMAGE_ARG_LOGSTASH_IMAGE_VERSION:-5.6.10}
    labels:
      deploy.config.commit: ${LABEL_DEPLOY_CONFIG_COMMIT:-unknown}
      deploy.config.name: ${LABEL_DEPLOY_CONFIG_NAME:-unknown}
      deploy.config.ref: ${LABEL_DEPLOY_CONFIG_REF:-unknown}
      deploy.util.commit: ${LABEL_DEPLOY_UTIL_COMMIT:-unknown}
      deploy.util.ref: ${LABEL_DEPLOY_UTIL_REF:-unknown}
      instance.name.short: ${LABEL_INSTANCE_NAME_SHORT:-standalone.elk-logstash}
      instance.name: ${LABEL_INSTANCE_NAME:-127.0.0.1/elk-logstash/standalone}
    networks:
      local-network:
        ipv4_address: ${IPV4_ADDRESS:-172.16.238.64}
        #ipv6_address: ${IPV6_ADDRESS:-2001:3984:3989::64}
    ports:
    - ${EXTERNAL_LOGSTASH_9600_PORT:-9600}:9600
    - ${EXTERNAL_LOGSTASH_5044_PORT:-5044}:5044
    - ${EXTERNAL_LOGSTASH_INPUT_JSON_TCP_PORT:-51401}:${INPUT_JSON_TCP_PORT:-51401}
    - ${EXTERNAL_LOGSTASH_INPUT_LINE_TCP_PORT:-51402}:${INPUT_LINE_TCP_PORT:-51402}
    restart: always
    volumes:
    - logstash-data:/usr/share/logstash/data
    - logstash-log:/usr/share/logstash/log
  logstash-redis-develop:
    container_name: ${CONTAINER_HOST_NAME:-standalone.elk}-logstash-redis
    hostname: ${CONTAINER_HOST_NAME:-standalone.elk}-logstash-redis
    image: redis:3.2.12-alpine
    labels:
      deploy.config.commit: ${LABEL_DEPLOY_CONFIG_COMMIT:-unknown}
      deploy.config.name: ${LABEL_DEPLOY_CONFIG_NAME:-unknown}
      deploy.config.ref: ${LABEL_DEPLOY_CONFIG_REF:-unknown}
      deploy.util.commit: ${LABEL_DEPLOY_UTIL_COMMIT:-unknown}
      deploy.util.ref: ${LABEL_DEPLOY_UTIL_REF:-unknown}
      instance.name.short: ${LABEL_INSTANCE_NAME_SHORT:-standalone.elk-logstash-redis}
      instance.name: ${LABEL_INSTANCE_NAME:-127.0.0.1/elk-logstash-redis/standalone}
    networks:
      local-network:
        ipv4_address: ${IPV4_ADDRESS:-172.16.238.65}
        #ipv6_address: ${IPV6_ADDRESS:-2001:3984:3989::65}
    ports:
    - ${EXTERNAL_LOGSTASH_REDIS_6379_PORT:-6379}:6379
    restart: always
    volumes:
    - logstash-redis-data:/data


networks:
  local-network:
    external: true
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
      - subnet: 172.16.238.0/24
      #- subnet: 2001:3984:3989::/64

volumes:
  logstash-data:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data/logstash/data
      o: bind
  logstash-log:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data/logstash/log
      o: bind
  logstash-redis-data:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data/logstash-redis
      o: bind
